name: first

on: push

jobs:
    build: 
        name: node environment
        runs-on: ubuntu-latest
        steps:
            - name: Setup Node.js environment
              uses: actions/setup-node@v3.5.1
